Throw when passed strings on Object.prototype
jshttp/statuses pull request #21
Opened 2020-12-24 22:17 UTC by EvanHahn

Because `'constructor' in Object.prototype`, `status('constructor')` would return `Object.prototype.constructor`. This was true for any all-lowercase key, which is currently `__proto__` and `constructor`.

Here's the meat of the change:

```diff
-  var map = {}
+  var map = Object.create(null)
```

2020-12-25 02:22 UTC, dougwilson requested changes
Unfortunately this object is a public API, so changing the prototype within the same major version is going to be painful. Can we implement the same behavior with something like `Object.prototype.hasOwnProperty` instead?

2020-12-25 19:22 UTC, EvanHahn commented
Updated with a new utility function, `getOwn`. Let me know if you'd prefer something lighter-weight.

2021-01-03 06:14 UTC, dougwilson commented
Thanks @EvanHahn ! I updated the PR to perform the check on all the lookups as well, so they are all guarded now as appropriate.

2021-01-03 06:14 UTC, dougwilson approved these changes

2021-01-03 06:15 UTC, merged